services:
  - type: web
    name: marconi-station-tracker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
