"""Initial

Revision ID: 6a33b3f2561d
Revises: 
Create Date: 2026-02-12 15:51:51.384157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a33b3f2561d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('skip_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_stations')
    )
    op.create_index('ix_stations_enabled', 'stations', ['enabled'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shazam_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('favorite_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_tracks')
    )
    op.create_index('ix_tracks_favorite_at', 'tracks', ['favorite_at'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='fk_plays_station_id_stations_id'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name='fk_plays_track_id_tracks_id'),
    sa.PrimaryKeyConstraint('id', name='pk_plays')
    )
    op.create_index('ix_plays_created_at', 'plays', ['created_at'], unique=False)
    op.create_index('ix_plays_station_id', 'plays', ['station_id'], unique=False)
    op.create_index('ix_plays_station_id_created_at', 'plays', ['station_id', 'created_at'], unique=False)
    op.create_index('ix_plays_track_id', 'plays', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plays_track_id', table_name='plays')
    op.drop_index('ix_plays_station_id_created_at', table_name='plays')
    op.drop_index('ix_plays_station_id', table_name='plays')
    op.drop_index('ix_plays_created_at', table_name='plays')
    op.drop_table('plays')
    op.drop_index('ix_tracks_favorite_at', table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('ix_stations_enabled', table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
